### ISSUE TITLE
AutoCatBoostCARMA error.

### ISSUE THREAD

**Issue by mallick84** [AdrianAntico/RemixAutoML#70] opened 2021-02-04 00:22 UTC
I am just trying to execute the example code of store data. But I am going through the different error.

**First execution.**
```
Results <- RemixAutoML::AutoCatBoostCARMA(
+   data,
+   TargetColumnName = "Weekly_Sales",
+   DateColumnName = "Date",
+   GroupVariables = c("Store","Dept"),
+   FC_Periods = 52,
+   TimeUnit = "week",
+   TargetTransformation = TRUE,
+   Lags = c(1:25, 51, 52, 53),
+   MA_Periods = c(1:25, 51, 52, 53),
+   CalendarVariables = TRUE,
+   TimeTrendVariable = TRUE,
+   DataTruncate = FALSE,
+   SplitRatios = c(1 - 2*30/143, 30/143, 30/143),
+   TaskType = "GPU",
+   EvalMetric = "MAE",
+   GridTune = FALSE,
+   GridEvalMetric = "mae",
+   ModelCount = 1,
+   NTrees = 20000,
+   PartitionType = "timeseries",
+   Timer = TRUE)
Error in RemixAutoML::AutoCatBoostCARMA(data2, TargetColumnName = "Weekly_Sales",  : 
  unused argument (GridEvalMetric = "made")

**Second error if I exclude 'GridEvalMetric'**  

```
Results <- RemixAutoML::AutoCatBoostCARMA(
+   data,
+   TargetColumnName = "Weekly_Sales",
+   DateColumnName = "Date",
+   GroupVariables = c("Store","Dept"),
+   FC_Periods = 52,
+   TimeUnit = "week",
+   TargetTransformation = TRUE,
+   Lags = c(1:25, 51, 52, 53),
+   MA_Periods = c(1:25, 51, 52, 53),
+   CalendarVariables = TRUE,
+   TimeTrendVariable = TRUE,
+   DataTruncate = FALSE,
+   SplitRatios = c(1 - 2*30/143, 30/143, 30/143),
+   TaskType = "GPU",
+   EvalMetric = "MAE",
+   GridTune = FALSE,
+   #GridEvalMetric = "mae",
+   ModelCount = 1,
+   NTrees = 20000,
+   PartitionType = "timeseries",
+   Timer = TRUE)
[1] "TimeUnits needs to be one of 'second', 'minute', 'hour', 'wday','mday', 'yday','week','wom','month', 'quarter', 'year'"
Error in catboost::catboost.train(learn_pool = TrainPool, test_pool = TestPool,  : 
  c:/program files (x86)/go agent/pipelines/buildmaster/catboost.git/catboost/cuda/cuda_lib/cuda_manager.cpp:201: Condition violated: `State == nullptr'
```

**If I use TaskType = "CPU" **

````Results <- RemixAutoML::AutoCatBoostCARMA(
+   data2,
+   TargetColumnName = "Weekly_Sales",
+   DateColumnName = "Date",
+   GroupVariables = c("Store","Dept"),
+   FC_Periods = 52,
+   TimeUnit = "week",
+   TargetTransformation = TRUE,
+   Lags = c(1:25, 51, 52, 53),
+   MA_Periods = c(1:25, 51, 52, 53),
+   CalendarVariables = TRUE,
+   TimeTrendVariable = TRUE,
+   DataTruncate = FALSE,
+   SplitRatios = c(1 - 2*30/143, 30/143, 30/143),
+   TaskType = "CPU",
+   EvalMetric = "MAE",
+   GridTune = FALSE,
+   #GridEvalMetric = "mae",
+   ModelCount = 1,
+   NTrees = 20000,
+   PartitionType = "timeseries",
+   Timer = TRUE)
[1] "TimeUnits needs to be one of 'second', 'minute', 'hour', 'wday','mday', 'yday','week','wom','month', 'quarter', 'year'"
Error in catboost::catboost.train(learn_pool = TrainPool, test_pool = TestPool,  : 
  c:/program files (x86)/go agent/pipelines/buildmaster/catboost.git/catboost/private/libs/options/bootstrap_options.cpp:38: MVS bootstrap supports per object sampling only.`

any suggestion, Please

Note: I am using catboost 0.24.3as I was facing erroron catboost 0.24.4

**Comment by AdrianAntico** [comment] 2021-02-04 00:46
@mallick84 Try out this version. Looks like you might be referencing an older version of the function. You'll have to keep in mind some of the new args, such as TrainOnFull. You set that to TRUE to train on full data and set it to FALSE to have the regression model insights returned.

```
# Build forecast
  Results <- RemixAutoML::AutoCatBoostCARMA(

    # data args
    data = data2,
    TimeWeights = 0.9999,
    TargetColumnName = "Weekly_Sales",
    DateColumnName = "Date",
    HierarchGroups = NULL,
    GroupVariables = c("Store","Dept"),
    TimeUnit = "weeks",
    TimeGroups = c("weeks","months"),

    # Production args
    TrainOnFull = TRUE,
    SplitRatios = c(1 - 2*30 / 143, 30 / 143, 30 / 143),
    PartitionType = "random",
    FC_Periods = 52,
    TaskType = "GPU",
    NumGPU = 1,
    Timer = TRUE,
    DebugMode = FALSE,

    # Target variable transformations
    TargetTransformation = FALSE,
    Methods = c("YeoJohnson", "BoxCox", "Asinh", "Log", "LogPlus1", "Sqrt", "Asin", "Logit"),
    Difference = FALSE,
    NonNegativePred = TRUE,
    RoundPreds = FALSE,

    # Calendar-related features
    CalendarVariables = c("week","wom","month","quarter"),
    HolidayVariable = c("USPublicHolidays"),
    HolidayLags = c(1,2,3),
    HolidayMovingAverages = c(2,3),

    # Lags, moving averages, and other rolling stats
    Lags = list("weeks" = c(1,2,3,4,5,8,9,12,13,51,52,53), "months" = c(1,2,6,12)),
    MA_Periods = list("weeks" = c(2,3,4,5,8,9,12,13,51,52,53), "months" = c(2,6,12)),
    SD_Periods = NULL,
    Skew_Periods = NULL,
    Kurt_Periods = NULL,
    Quantile_Periods = NULL,
    Quantiles_Selected = NULL,

    # Bonus features
    AnomalyDetection = NULL,
    XREGS = NULL,
    FourierTerms = 0,
    TimeTrendVariable = TRUE,
    ZeroPadSeries = NULL,
    DataTruncate = FALSE,

    # ML grid tuning args
    GridTune = FALSE,
    PassInGrid = NULL,
    ModelCount = 5,
    MaxRunsWithoutNewWinner = 50,
    MaxRunMinutes = 60*60,

    # ML evaluation output
    PDFOutputPath = NULL,
    SaveDataPath = NULL,
    NumOfParDepPlots = 0L,

    # ML loss functions
    EvalMetric = "RMSE",
    EvalMetricValue = 1,
    LossFunction = "RMSE",
    LossFunctionValue = 1,

    # ML tuning args
    NTrees = 1000L,
    Depth = 6L,
    L2_Leaf_Reg = NULL,
    LearningRate = NULL,
    Langevin = FALSE,
    DiffusionTemperature = 10000,
    RandomStrength = 1,
    BorderCount = 254,
    RSM = NULL,
    GrowPolicy = "SymmetricTree",
    BootStrapType = "Bayesian",
    ModelSizeReg = 0.5,
    FeatureBorderType = "GreedyLogSum",
    SamplingUnit = "Group",
    SubSample = NULL,
    ScoreFunction = "Cosine",
    MinDataInLeaf = 1)
```

**Comment by mallick84** [comment] 2021-02-05 03:59
Thank you. let me check it.

**Comment by mallick84** [comment] 2021-02-06 02:04
I am still stuck to resolve it.

### On Catboost 0.24.3 
`# Load Walmart Data from Remix Institute's Box Account----
> data1 <- data.table::fread("https://remixinstitute.box.com/shared/static/9kzyttje3kd7l41y1e14to0akwl9vuje.csv")
 Downloaded 3087910 bytes...
> # Subset for Stores / Departments With Full Series (143 time points each)----
> data2 <- data1[, Counts := .N, by = c("Store","Dept")][
+   Counts == 143][, Counts := NULL]
> # Subset Columns (remove IsHoliday column)----
> keep <- c("Store","Dept","Date","Weekly_Sales")
> data2 <- data2[, ..keep]
> data2 %>% glimpse()
Rows: 380,380
Columns: 4
$ Store        <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...
$ Dept         <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...
$ Date         <date> 2010-02-05, 2010-02-12, 2010-02-19, 2010-02-26, 2...
$ Weekly_Sales <dbl> 24924.50, 46039.49, 41595.55, 19403.54, 21827.90, ...
> # Build forecast
> Results <- RemixAutoML::AutoCatBoostCARMA(
+   
+   # data args
+   data = data2,
+   TimeWeights = 0.9999,
+   TargetColumnName = "Weekly_Sales",
+   DateColumnName = "Date",
+   HierarchGroups = NULL,
+   GroupVariables = c("Store","Dept"),
+   TimeUnit = "weeks",
+   TimeGroups = c("weeks","months"),
+   
+   # Production args
+   TrainOnFull = TRUE,
+   SplitRatios = c(1 - 2*30 / 143, 30 / 143, 30 / 143),
+   PartitionType = "random",
+   FC_Periods = 52,
+   TaskType = "GPU",
+   NumGPU = 1,
+   Timer = TRUE,
+   DebugMode = FALSE,
+   
+   # Target variable transformations
+   TargetTransformation = FALSE,
+   Methods = c("YeoJohnson", "BoxCox", "Asinh", "Log", "LogPlus1", "Sqrt", "Asin", "Logit"),
+   Difference = FALSE,
+   NonNegativePred = TRUE,
+   RoundPreds = FALSE,
+   
+   # Calendar-related features
+   CalendarVariables = c("week","wom","month","quarter"),
+   HolidayVariable = c("USPublicHolidays"),
+   HolidayLags = c(1,2,3),
+   HolidayMovingAverages = c(2,3),
+   
+   # Lags, moving averages, and other rolling stats
+   Lags = list("weeks" = c(1,2,3,4,5,8,9,12,13,51,52,53), "months" = c(1,2,6,12)),
+   MA_Periods = list("weeks" = c(2,3,4,5,8,9,12,13,51,52,53), "months" = c(2,6,12)),
+   SD_Periods = NULL,
+   Skew_Periods = NULL,
+   Kurt_Periods = NULL,
+   Quantile_Periods = NULL,
+   Quantiles_Selected = NULL,
+   
+   # Bonus features
+   AnomalyDetection = NULL,
+   XREGS = NULL,
+   FourierTerms = 0,
+   TimeTrendVariable = TRUE,
+   ZeroPadSeries = NULL,
+   DataTruncate = FALSE,
+   
+   # ML grid tuning args
+   GridTune = FALSE,
+   PassInGrid = NULL,
+   ModelCount = 5,
+   MaxRunsWithoutNewWinner = 50,
+   MaxRunMinutes = 60*60,
+   
+   # ML evaluation output
+   PDFOutputPath = NULL,
+   SaveDataPath = NULL,
+   NumOfParDepPlots = 0L,
+   
+   # ML loss functions
+   EvalMetric = "RMSE",
+   EvalMetricValue = 1,
+   LossFunction = "RMSE",
+   LossFunctionValue = 1,
+   
+   # ML tuning args
+   NTrees = 1000L,
+   Depth = 6L,
+   L2_Leaf_Reg = NULL,
+   LearningRate = NULL,
+   Langevin = FALSE,
+   DiffusionTemperature = 10000,
+   RandomStrength = 1,
+   BorderCount = 254,
+   RSM = NULL,
+   GrowPolicy = "SymmetricTree",
+   BootStrapType = "Bayesian",
+   ModelSizeReg = 0.5,
+   FeatureBorderType = "GreedyLogSum",
+   SamplingUnit = "Group",
+   SubSample = NULL,
+   ScoreFunction = "Cosine",
+   MinDataInLeaf = 1)
Learning rate set to 0.093159
Error in catboost::catboost.train(learn_pool = TrainPool, test_pool = TestPool,  : 
  c:/program files (x86)/go agent/pipelines/buildmaster/catboost.git/catboost/cuda/cuda_lib/cuda_base.h:281: CUDA error 35: CUDA driver version is insufficient for CUDA runtime version`

### After updating catboost to 0.24.4

`# Load Walmart Data from Remix Institute's Box Account----
> data1 <- data.table::fread("https://remixinstitute.box.com/shared/static/9kzyttje3kd7l41y1e14to0akwl9vuje.csv")
 Downloaded 3087910 bytes...> # Subset Columns (remove IsHoliday column)----
keep <- c("Store","Dept","Date","Weekly_Sales")
> data2 <- data2[, ..keep]
> data2 %>% glimpse()
Rows: 380,380
Columns: 4
$ Store        <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...
$ Dept         <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...
$ Date         <date> 2010-02-05, 2010-02-12, 2010-02-19, 2010-02-26, 2010-03...
$ Weekly_Sales <dbl> 24924.50, 46039.49, 41595.55, 19403.54, 21827.90, 21043....
> # Subset for Stores / Departments With Full Series (143 time points each)----
> data2 <- data1[, Counts := .N, by = c("Store","Dept")][
+   Counts == 143][, Counts := NULL]
> # Build forecast
> Results <- RemixAutoML::AutoCatBoostCARMA(
+   
+   # data args
+   data = data2,
+   TimeWeights = 0.9999,
+   TargetColumnName = "Weekly_Sales",
+   DateColumnName = "Date",
+   HierarchGroups = NULL,
+   GroupVariables = c("Store","Dept"),
+   TimeUnit = "weeks",
+   TimeGroups = c("weeks","months"),
+   
+   # Production args
+   TrainOnFull = TRUE,
+   SplitRatios = c(1 - 2*30 / 143, 30 / 143, 30 / 143),
+   PartitionType = "random",
+   FC_Periods = 52,
+   TaskType = "GPU",
+   NumGPU = 1,
+   Timer = TRUE,
+   DebugMode = FALSE,
+   
+   # Target variable transformations
+   TargetTransformation = FALSE,
+   Methods = c("YeoJohnson", "BoxCox", "Asinh", "Log", "LogPlus1", "Sqrt", "Asin", "Logit"),
+   Difference = FALSE,
+   NonNegativePred = TRUE,
+   RoundPreds = FALSE,
+   
+   # Calendar-related features
+   CalendarVariables = c("week","wom","month","quarter"),
+   HolidayVariable = c("USPublicHolidays"),
+   HolidayLags = c(1,2,3),
+   HolidayMovingAverages = c(2,3),
+   
+   # Lags, moving averages, and other rolling stats
+   Lags = list("weeks" = c(1,2,3,4,5,8,9,12,13,51,52,53), "months" = c(1,2,6,12)),
+   MA_Periods = list("weeks" = c(2,3,4,5,8,9,12,13,51,52,53), "months" = c(2,6,12)),
+   SD_Periods = NULL,
+   Skew_Periods = NULL,
+   Kurt_Periods = NULL,
+   Quantile_Periods = NULL,
+   Quantiles_Selected = NULL,
+   
+   # Bonus features
+   AnomalyDetection = NULL,
+   XREGS = NULL,
+   FourierTerms = 0,
+   TimeTrendVariable = TRUE,
+   ZeroPadSeries = NULL,
+   DataTruncate = FALSE,
+   
+   # ML grid tuning args
+   GridTune = FALSE,
+   PassInGrid = NULL,
+   ModelCount = 5,
+   MaxRunsWithoutNewWinner = 50,
+   MaxRunMinutes = 60*60,
+   
+   # ML evaluation output
+   PDFOutputPath = NULL,
+   SaveDataPath = NULL,
+   NumOfParDepPlots = 0L,
+   
+   # ML loss functions
+   EvalMetric = "RMSE",
+   EvalMetricValue = 1,
+   LossFunction = "RMSE",
+   LossFunctionValue = 1,
+   
+   # ML tuning args
+   NTrees = 1000L,
+   Depth = 6L,
+   L2_Leaf_Reg = NULL,
+   LearningRate = NULL,
+   Langevin = FALSE,
+   DiffusionTemperature = 10000,
+   RandomStrength = 1,
+   BorderCount = 254,
+   RSM = NULL,
+   GrowPolicy = "SymmetricTree",
+   BootStrapType = "Bayesian",
+   ModelSizeReg = 0.5,
+   FeatureBorderType = "GreedyLogSum",
+   SamplingUnit = "Group",
+   SubSample = NULL,
+   ScoreFunction = "Cosine",
+   MinDataInLeaf = 1)
Error in .Call("CatBoostHashStrings_R", as.character(preprocessed[[column_index]])) : 
  "CatBoostHashStrings_R" not resolved from current namespace (catboost)`

**Anything I am missing?**

**Comment by AdrianAntico** [comment] 2021-02-06 02:53
Catboost v0.24.4 isn't working for R currently. The maintainers said it will be fixed for their next release so you'll have to use v0.24.3 for now. https://github.com/catboost/catboost/issues/1525

As for setting up the function to work correctly, check out the example in the help file, which is at the bottom of it. It shows you how to tune the function. Type this into your R console to see it: ?RemixAutoML::AutoCatBoostCARMA

**Closed by AdrianAntico** 2021-02-06 02:53 UTC
